micronaut:
  application:
    name: acmeFilms
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/acme_films?verifyServerCertificate=false&useSSL=false`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:123456Pwd@}
    dialect: MYSQL
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}